export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'

export const GET_BOOKS = 'GET_BOOKS'
export const RECEIVE_BOOK = 'RECEIVE_BOOK'
export const RECEIVE_BOOKS = 'RECEIVE_BOOKS'
export const RECEIVE_MYBOOKS = 'RECEIVE_MYBOOKS'
export const RECEIVE_BOOKSEARCH = 'RECEIVE_BOOKSEARCH'
